export const guestData = [
  {
    key: '1',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '2',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '3',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '4',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '5',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '6',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '7',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '8',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '9',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '10',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '11',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '12',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '13',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '14',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '15',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '16',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '17',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '18',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '19',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '20',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '21',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '22',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '23',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '24',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '25',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '26',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '27',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '28',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '29',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '30',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '31',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '32',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '33',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  },
  {
    key: '34',
    name: 'John',
    age: 42,
    address: '10 Downing Street',
  },
  {
    key: '35',
    name: 'Mike',
    age: 32,
    address: '10 Downing Street',
  }
];